import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from "react";
import { Sparkles, BookOpen, History, BarChart3, PlusCircle, LogOut, ShieldCheck, User as UserIcon } from "lucide-react";
export const Navbar = ({ user, activeTab, onTabChange, onNewEntry, onSignOut, entriesCount, }) => {
    return (_jsx("header", { id: "main-navbar", className: "sticky top-0 z-40 bg-[#fdfbf7]/90 backdrop-blur-md border-b border-[#e7e2d6]", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-xl bg-[#342f2b] text-[#fdfbf7] flex items-center justify-center shadow-xs", children: _jsx(Sparkles, { className: "w-5 h-5 text-[#e0b07a]" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-serif text-xl font-bold tracking-tight text-[#2d2926]", children: "AI Journal" }), _jsxs("span", { className: "hidden sm:inline-flex items-center gap-1 text-[11px] font-medium bg-[#f5efe4] text-[#825c34] border border-[#e8dbcc] px-2 py-0.5 rounded-full", children: [_jsx(Sparkles, { className: "w-2.5 h-2.5" }), " Gemini 3.6 Flash"] })] }), _jsx("p", { className: "text-xs text-[#7d756c] hidden md:block", children: "Reflective thinking & structured cognition" })] })] }), user && (_jsxs("nav", { className: "flex items-center gap-1 bg-[#f3eee4] p-1 rounded-xl border border-[#e5dfd2]", children: [_jsxs("button", { id: "nav-tab-editor", type: "button", onClick: () => onTabChange("editor"), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-sm font-medium transition-all ${activeTab === "editor"
                                    ? "bg-[#ffffff] text-[#2d2926] shadow-xs"
                                    : "text-[#696157] hover:text-[#2d2926] hover:bg-[#e9e3d7]/60"}`, children: [_jsx(BookOpen, { className: "w-4 h-4 text-[#5c544b]" }), _jsx("span", { children: "Reflect" })] }), _jsxs("button", { id: "nav-tab-history", type: "button", onClick: () => onTabChange("history"), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-sm font-medium transition-all ${activeTab === "history"
                                    ? "bg-[#ffffff] text-[#2d2926] shadow-xs"
                                    : "text-[#696157] hover:text-[#2d2926] hover:bg-[#e9e3d7]/60"}`, children: [_jsx(History, { className: "w-4 h-4 text-[#5c544b]" }), _jsx("span", { children: "History" }), entriesCount > 0 && (_jsx("span", { className: "text-xs bg-[#e5ded1] text-[#423c34] font-semibold px-1.5 py-0.2 rounded-full", children: entriesCount }))] }), _jsxs("button", { id: "nav-tab-insights", type: "button", onClick: () => onTabChange("insights"), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-lg text-sm font-medium transition-all ${activeTab === "insights"
                                    ? "bg-[#ffffff] text-[#2d2926] shadow-xs"
                                    : "text-[#696157] hover:text-[#2d2926] hover:bg-[#e9e3d7]/60"}`, children: [_jsx(BarChart3, { className: "w-4 h-4 text-[#5c544b]" }), _jsx("span", { className: "hidden sm:inline", children: "Insights" })] })] })), _jsx("div", { className: "flex items-center gap-2.5", children: user ? (_jsxs(_Fragment, { children: [_jsxs("button", { id: "btn-new-entry-header", type: "button", onClick: onNewEntry, className: "hidden sm:flex items-center gap-2 bg-[#342f2b] text-[#fdfbf7] hover:bg-[#25211e] px-3.5 py-2 rounded-xl text-sm font-medium shadow-xs transition-colors", children: [_jsx(PlusCircle, { className: "w-4 h-4 text-[#e0b07a]" }), _jsx("span", { children: "New Reflection" })] }), _jsxs("div", { className: "flex items-center gap-2 pl-2 border-l border-[#e7e2d6]", children: [_jsxs("div", { className: "flex items-center gap-2 bg-[#f5f1e8] border border-[#e5dfd2] px-2.5 py-1.5 rounded-xl text-xs text-[#524b42]", children: [user.photoURL ? (_jsx("img", { src: user.photoURL, alt: "Avatar", className: "w-5 h-5 rounded-full object-cover border border-[#d6cebf]", referrerPolicy: "no-referrer" })) : (_jsx("div", { className: "w-5 h-5 rounded-full bg-[#dfd7c8] text-[#524b42] flex items-center justify-center", children: _jsx(UserIcon, { className: "w-3 h-3" }) })), _jsx("span", { className: "font-medium max-w-[110px] truncate hidden md:inline", children: user.displayName || user.email || "Explorer" }), user.isAnonymous && (_jsx("span", { className: "text-[10px] bg-[#eedfcb] text-[#7a4e1d] font-semibold px-1 rounded", children: "Guest" }))] }), _jsx("button", { id: "btn-signout", type: "button", onClick: onSignOut, title: "Sign Out", className: "p-2 text-[#7d756c] hover:text-[#9e3a2f] hover:bg-[#faeae7] rounded-xl transition-colors", children: _jsx(LogOut, { className: "w-4 h-4" }) })] })] })) : (_jsxs("div", { className: "flex items-center gap-1.5 text-xs text-[#5f6954] font-medium bg-[#eef3eb] border border-[#d3ddce] px-2.5 py-1 rounded-full", children: [_jsx(ShieldCheck, { className: "w-4 h-4 text-[#4f5c44]" }), _jsx("span", { children: "Isolated Firestore Auth" })] })) })] }) }) }));
};
